# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - delivery-shop-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B3F6D569C374D02B14AEED044288F4E }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_908A6F2373E74A3A8A4D55A6E44F6C04  }}

    - name: Build and push container image to registry
      run: |
        docker build -t victorassiso/pizza-shop-api:latest .
        docker login -u ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B3F6D569C374D02B14AEED044288F4E }} -p ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_908A6F2373E74A3A8A4D55A6E44F6C04 }}
        docker push victorassiso/pizza-shop-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'delivery-shop-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_032137201C994C0DA4C171810AE58B2C }}
        images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B3F6D569C374D02B14AEED044288F4E }}/pizza-shop-api:latest'
      env:
        NODE_ENV: production
        PORT: 80
        WEBSITED_PORT: 8080
        # Auth
        JWT_SECRET: stockwisenode
        # Database
        DATABASE_URL: "postgres://pizza_shop_db_juaa_user:ecoSJZDiC4tyElE8RcRzWhDh3i2MS35M@dpg-cmo3jdg21fec73cugddg-a.ohio-postgres.render.com/pizza_shop_db_juaa"